binary_sensor:
  - name: "Taku Sleep Mode"
    unique_id: taku_sleep_mode
    state: >
      {{ is_state('input_boolean.taku_sleep_mode', 'on') }}
    icon: >
      {% if is_state('binary_sensor.taku_sleep_mode', 'on') %}
        mdi:sleep
      {% else %}
        mdi:sleep-off
      {% endif %}
