sensor:
  - name: "Upstairs Sans Comms Rack 4PM Net Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >
      {% set upstairs=states('sensor.upstairs_power')|float %}
      {# TODO(conall): Iterate over integration_entities('Shelly: Comms Rack Pro 4PM')|endwith:"power" #}
      {% set comms_rack_1=states('sensor.unifi_switch_power')|float %}
      {% set comms_rack_2=states('sensor.unifi_dream_machine_power')|float %}
      {% set comms_rack_3=states('sensor.comms_rack_powerstrip_power')|float %}
      {% set comms_rack_4=states('sensor.megatron_power')|float %}
      {{ (upstairs - (comms_rack_1 + comms_rack_2 + comms_rack_3 + comms_rack_4))|float(default=0) }}
