- platform: universal
  name: home_cinema
  unique_id: multi_device_home_cinema
  friendly_name: "Home Cinema"
  children:
    - media_player.pioneer_vsx_934
    - media_player.50pus8555_12
    - media_player.sitting_room  # Sonos Port
    - media_player.sitting_room_appletv
  commands:
    turn_on:
      service: switch.home_cinema_turn_on
      target:
        entity_id: switch.home_cinema_tv
    turn_off:
      service: switch.home_cinema_turn_of
      target:
        entity_id: switch.home_cinema_tv
    volume_up:
      service: switch.home_cinema_turn_on
      target:
        entity_id: switch.home_cinema_volume_up
    volume_down:
      service: switch.turn_on
      target:
        entity_id: switch.home_cinema_volume_down
    volume_mute:
      service: switch.turn_on
      target:
        entity_id: switch.home_cinema_mute
    select_source:
      service: media_player.home_cinema_select_source
      target:
        entity_id: media_player.pioneer_vsx_934
      data:
        source: "{{ source }}"
    volume_set:
      service: media_player.home_cinema_volume_set
      target:
        entity_id: media_player.pioneer_vsx_934
      data:
        volume_level: "{{ volume_level }}"
