id: '1698610029172'
alias: Taku Bedtime
description: Puts the house to sleep for the night - turns off the front garden, back garden, downstairs and bathroom lights, then enables the Bathroom Bedtime On scene in Hue.
trigger:
- device_id: b14b7c6afc5785c4323a208916939bb2
  domain: hue
  platform: device
  type: long_release
  subtype: 4
  unique_id: 0984d4be-25ad-448e-ad50-eac92cd4662c
condition:
- condition: sun
  after: sunset
action:
- metadata: {}
  data: {}
  target:
    area_id:
    - front_garden
    - back_garden
    - sitting_room
    - kitchen
    - hall
    - family_room
    - home_cinema
    - bathroom
  action: light.turn_off
- target:
    entity_id: scene.bathroom_bedtime_on_nightlight
  metadata: {}
  action: scene.turn_on
mode: single
