id: '1746886008844'
alias: Update Apple Watch
description: ''
triggers: []
conditions: []
actions:
- action: notify.conall_phone
  metadata: {}
  data:
    data:
      message: update_complications
mode: single
