# Home Assistant configuration for Energia Smart Data - 15 electricity tariffs
# This configuration creates a REST sensor to download the tariff data
# and then creates template sensors for each price component

# REST Sensor to download the JSON file
resource: "https://github.com/conallob/ireland-electricity-tariffs/releases/latest/download/home_assistant_tariffs.json"
scan_interval: 86400  # Update once per day
sensor:
  - name: "Ireland Electricity Tariffs"
    value_template: "OK"
    json_attributes_path: "$.tariffs"
    json_attributes:
    - "electric-ireland-smart-dual-fuel"
